# Generated by Django 4.2.30 on 2026-04-29 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightpost',
            name='body_html',
            field=models.TextField(blank=True),
        ),
    ]
